### ISSUE TITLE
Bind an array to v-model?

### ISSUE THREAD

**Issue by peaeater** [vue-bulma/switch#10]
Is it possible to bind a model to the switch that isn't boolean? How does one use the switch in place of a checkbox in a form if it has no value attribute? I would like to be able bind an array to v-model, as described in Vue.js v2 guide on forms: [https://vuejs.org/v2/guide/forms.html#Checkbox](https://vuejs.org/v2/guide/forms.html#Checkbox).

**Comment by fundon** [comment]
Landed in https://github.com/vue-bulma/switch/blob/next/src/Switch.vue 2.0.0-alpha.0
