### ISSUE TITLE
The first input event is wrong when the initial state is checked

### ISSUE THREAD

**Issue by KyleXie** [vue-bulma/switch#13]
```
<vb-switch type="primary" v-model=active"
        @input="switchEnabled(checked)" />
```
if the `active` is true, you can see the switch is on, but when you try to turn is off, you need to tap it twice, the first time after you tap it, it emit an input event with checked state true, it should be false.

**Comment by heygambo** [comment]
@KyleXie can you provide a jsfiddle or code pen? I didn't have this issue.

**Comment by KyleXie** [comment]
Hi @nerdyglasses ,

Thanks for you reply. You can see it from here: [#13 demo](http://jsfiddle.net/KyleXie/ogopq27u/). The reason of this bug is the checked property of the input is not sync with the value of the switch, so when we bind the value with v-model and the initial value of v-model is true, the switch looks on in styling, but the checked property of the input is still false. We need to tap it once to sync the checked property.

This bug only shows on version 1.0.5, it's ok on 1.0.4.

**Comment by KyleXie** [comment]
@nerdyglasses Hi, sorry the jsfiddle link in the last comment is not correct, please see it here:[http://jsfiddle.net/KyleXie/ogopq27u/22/](http://jsfiddle.net/KyleXie/ogopq27u/22/)

**Comment by heygambo** [comment]
@KyleXie I've found what's wrong with the component but I also found a few things that we're wrong in your example.

You were right, it really has an issue.

## why the component doesn't work

The main reason why it didn't work was that the input's `checked` value was still `false` in the beginning even though the components value was `true`

Here is an updated version how it should be fixed in my opinion:
http://jsfiddle.net/gambo/xwgf0j5f/2/

## about your fiddle
In your example you've had this line: 
```
<my-switch type="primary" v-model="active" @input="onSwitch"></switch>
```

Note that `v-model` is syntactic sugar for `:value="variable" @input="value => { this.variable = value }"`

That means you've had 2 `@input` listeners in your code like this:

```
<my-switch type="primary" :value="active" @input="value => { this.active = value }" @input="onSwitch"></switch>
```

**Comment by KyleXie** [comment]
@nerdyglasses Thanks for your suggestion, I made a new commit about it, please have a check.

About the two listeners issue in my code, my actual  use case is like this:

```
<tr v-for="obj in objects">
  <my-switch type="primary" v-model="obj.active" @input="onSwitch(obj) />
</tr>
```
I need to bind the model to one obj and distinguish which switch it it when the state changes.

```
onSwitch (obj) {
  // do something with obj
}
```
How should I handle this kind of situation?

**Comment by heygambo** [comment]
hey @KyleXie you can just have a watcher like this: 

```
<template>
  <my-switch v-model="switchValue" />
</template>

<script type="javascript">
export default {
  name: 'SomeComponent',
  data () {
    return {
      switchValue: false
    }
  },
  watch: {
    switchValue (switchValue) {
      // Do something with value
    }
  }
}
</script>
```

**Comment by KyleXie** [comment]
@nerdyglasses You have one switch in your example, but in my situation, there're probably 20 switches, switch1Value, switch2Value ... switch20Value may not be a good idea.

**Comment by fundon** [comment]
Checkout https://github.com/vue-bulma/switch/blob/next/src/Switch.vue 2.0.0-alpha.0
