### ISSUE TITLE
emit input

### ISSUE THREAD

**Issue by johanpedroo** [vue-bulma/switch#2]
why not uses 
`this.$emit('input', val)`
too? This would make it possible to use v-model in parents too.
with
`<label class="switch" :class="{ [`is-${type}`]: type, [`is-${size}`]: size, ['checked']: value }">`
all works perfectly.

**Comment by fundon** [comment]
Thanks!
Landed in https://github.com/vue-bulma/switch/commit/f420aa902ea8698be3d87980a55f16f401956c29.
