### ISSUE TITLE
Always `off` on `init`

### ISSUE THREAD

**Issue by webgodo** [vue-bulma/switch#3]
I've used it in my project and it works fine. But it's initial view is not correct. I mean I've binded it as following:
`<vb-switch type="success" size="large" v-model="form.data.isActive"></vb-switch>`

But it is always `off` on init.

**Comment by webgodo** [comment]
Even with line below:
`<vb-switch type="success" size="large" checked v-model="form.data.isActive"></vb-switch>`

*As you see, I've added `checked` to it*, it still doesn't work correctly on init. In this state, it is always `on` (checked) on init

I think it's because my `model` name is not `value`... so how should it be done with `v-model="form.data.isActive"`?

**Comment by webgodo** [comment]
👎 No answer after about a week :(

**Comment by luventa** [comment]
Sorry for replying late. Too busy with other works...
You can try `:checked="value" v-model="value"`

For example:
`<vb-switch type="success" size="large" :checked="value" v-model="value"></vb-switch>`

Please let me know if I have any misunderstandings

Thank you for raising the issue!

**Comment by webgodo** [comment]
It works now, but I made another change too.
I put the `vb-switch` in a `<div>` with `v-if` directive like so:

```
<div class="column is-one-third" v-if="form.data.isMain !== null">
  <vb-switch type="success"
    size="large"
    :checked="form.data.isMain"
    v-model="form.data.isMain"></vb-switch>
</div>
```
