### ISSUE TITLE
Vuex Usage

### ISSUE THREAD

**Issue by cloud-tribal** [vue-bulma/switch#7]
Great widget! Thank you for making this.

How would you use it with Vuex?

It seems standard event handlers don't get exposed to the component.

**Comment by luventa** [comment]
this component tirggers an 'input' event. So the parent component can use `v-on:input="methodName"` to handle the child event. Then vuex methods can be called inside the handler method `methodName`.
[Using-v-on-with-Custom-Events](http://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events)
